export const BLABBER_BASE_URL = 'http://localhost:4000'
export const VERSION = '/v1/'
export const USER = 'user/'
export const CHAT = 'chat/'
export const LOGIN = 'login'
export const SIGN_UP = 'sign-up'